language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
cache:
    - cargo: true
    - apt: true
addons:
    apt:
        packages:
            - libdbus-1-dev
before_script:
    - rustup component add rustfmt
script:
    - rustfmt src/* && git diff --quiet
    - cd test && ./test.sh
